openapi: 3.0.1
info:
  title: Month and Math API
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /solution/subtract:
    post:
      tags:
        - math-solution-controller
      operationId: subtractNumbers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MathSolution'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolution'
  /solution/multiply:
    post:
      tags:
        - math-solution-controller
      operationId: multiplyNumbers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MathSolution'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolution'
  /solution/divide:
    post:
      tags:
        - math-solution-controller
      operationId: divideNumbers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MathSolution'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolution'
  /solution/add:
    post:
      tags:
        - math-solution-controller
      operationId: addNumbers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MathSolution'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolution'
  /randomMonth:
    get:
      tags:
        - month-controller
      operationId: randomNum
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MonthService'
  /months:
    get:
      tags:
        - month-controller
      operationId: getMonthNumber
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MonthService'
  /months/{monthNumber}:
    get:
      tags:
        - month-controller
      operationId: getMonthAndNumber
      parameters:
        - name: monthNumber
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MonthService'
components:
  schemas:
    MathSolution:
      type: object
      properties:
        operand1:
          type: integer
          format: int32
        operand2:
          type: integer
          format: int32
        operation:
          type: string
        answer:
          type: integer
          format: int32
    MonthService:
      required:
        - name
        - number
      type: object
      properties:
        number:
          type: integer
          format: int32
        name:
          type: string
